when:
  - event: push
    branch: main

steps:
  - name: build
    image: 1.26.3-alpine3.23
    commands:
      - go mod tidy
      - go build -o www cmd/website/main.go
  - name: deploy
    image: alpine:latest
    commands: |
      apk add --no-cache openssh-client

      mkdir -p ~/.ssh
      echo "$SSH_KEY" > ~/.ssh/id_rsa
      chmod 600 ~/.ssh/id_rsa

      ssh -tt -o StrictHostKeyChecking=no uncertainty@192.168.178.81 "rm -r $COPY_TO || true"
      scp -o StrictHostKeyChecking=no -r $COPY_FROM uncertainty@192.168.178.81:$COPY_TO

      ssh -tt -o StrictHostKeyChecking=no uncertainty@192.168.178.31 "doas service www-gay-leggy-dev restart"
    environment:
      COPY_FROM: www
      COPY_TO: /home/uncertainty/www/gay_leggy_dev/www
      SSH_KEY:
        from_secret: ssh_key
